

#ifndef OPENGL_PROJECT_FREECAMCONTROLS_H
#define OPENGL_PROJECT_FREECAMCONTROLS_H

enum FreeCamControls {
    TOGGLE_FREECAM,
    FASTER_FREECAM,
    SLOWER_FREECAM,
    RESET_SPEED_FREECAM
};

#endif //OPENGL_PROJECT_FREECAMCONTROLS_H
